spring:
  application:
    name: rabbitmq
  rabbitmq:
    host: 111.231.100.226
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    #确认消息已发送到交换机(Exchange)
    publisher-confirms: true
    #确认消息已发送到队列(Queue)
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual
        concurrency: 5
        max-concurrency: 10
        prefetch: 1
  #配置邮件信息
  mail:
      default-encoding: utf-8
      # 主机地址
      host: smtp.126.com
      # 邮箱名
      username: 13676623960@163.com
      # 授权码（不是密码）
      password: IFLSBMMNKGUMTFFV
  redis:
      database: 0
          host: 111.231.100.226
          port: 6379
          password: CCWTNccwtn44223
server:
  port: 8021